org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_id=woodwalkers_spellbooks
mod_name=Woodwalkers Spell Books
mod_license=MIT
mod_version=0.3.0-BETA
mod_group_id=com.github.jodevnull
mod_authors=jo-devnull
mod_description=A shapeshifting spell to transform into other mobs

# Minecraft
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
mapping_channel=official
mapping_version=1.20.1

# Forge
forge_version=47.4.13
forge_version_range=[47,)
loader_version_range=[47,)

# Dependencies
irons_spells   = 1.20.1-3.15.6
ironslib       = irons-lib-1492763:7907335
geckolib       = geckolib-388172:7553267
curios         = curios-309927:6418456
playeranimator = playeranimator-658587:4587214
woodwalkers    = woodwalkers-868922:7776200
crafted_core   = crafted-core-923377:7575385
