org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_id=woodwalkers_spellbooks
mod_name=Woodwalkers SpellBooks
mod_license=MIT
mod_version=0.3.0-BETA
mod_group_id=com.github.jodevnull
mod_authors=jo-devnull
mod_description=A useful spell to shapeshift into other mobs.

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

# NeoForge
neo_version=21.1.227
neo_version_range=[21,)
loader_version_range=[4,)

# Dependencies
irons_spells   = 1.21.1-3.15.6
geckolib       = geckolib-388172:7707149
curios         = curios-309927:6529130
ironslib       = irons-lib-1492763:7907336
playeranimator = playeranimator-658587:7389814

woodwalkers    = woodwalkers-868922:7776214
craftedcore    = crafted-core-923377:7575403